name: Deploy Docs

on:
  push:
    branches:
      - readthedocs

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Actions permissions
        run: |
          echo "GitHub Actions permissions:"
          echo "GITHUB_TOKEN: ${{ github.token }}"
          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Debug git configuration
        run: |
          git config --list
          git remote -v
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install sphinx
      - name: Build documentation
        run: cd docs && sphinx-build -b html . _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          force_orphan: true
